AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Naming/PredicateName:
  NameWhitelist:
    - is_a?
    - is_logged_in?

Naming/AccessorMethodName:
  Enabled: false

Rails/SkipsModelValidations:
  Whitelist:
    - update_attribute
    - update_columns
    - toggle!

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20
